/*
 * Generated by erpcgen 1.7.1 on Thu Mar  7 19:11:19 2019.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_touch_update_h_)
#define _erpc_touch_update_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10701 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief TouchUpdateService identifiers */
enum _TouchUpdateService_ids
{
    kTouchUpdateService_service_id = 1,
    kTouchUpdateService_erpcTouchUpdate_id = 1,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name TouchUpdateService
//@{
void erpcTouchUpdate(int32_t percent);
//@} 

#if defined(__cplusplus)
}
#endif

#endif // _erpc_touch_update_h_
